<?php include "includes/header.php"?>

<h3>Plain English Science: Drug-Induced Trichotillomania - Four Case Studies</h3>
 	<p id="sub">by Matthew Toles March 26, 2017</p>
	<p id="pmar">Though the root causes of typical trichotillomania are poorly understood and hypotheses range from genetics, glutamate regulation, trauma, and many combinations thereof, a few case studies over the years have been able to induce trichotillomania using drugs. To be clear, they didn’t induce trich on purpose, they found that various substances incidentally cause hair pulling and that stopping these substances stopped hair pulling. They then wrote it down, published the science, and called it a day. So far, no studies seem to exist on trich as a side effect of any medication, but BFRB research is relatively young and case studies, though anecdotal, point a huge flashing arrow saying hey, look over here. Hopefully it is only a matter of time (and funding) before the research catches up and we get some proper peer-reviewed studies on substances that might cause or exacerbate trich symptoms. Anyway, here’s the science.</p>
</div>
<h4>Adderall</h4>
<p id="pmar">In 2013, a 12-year-old girl was placed on daily Adderall (dextroamphetamine/amphetamine, both stimulants) to treat ADHD. Soon after, parents noticed hair pulling mainly from the frontal scalp. After determining no other underlying causes of pulling such as OCD, trauma, or PTSD, Adderall was replaced with guanfacine and hair pulling symptoms subsided permanently.</p>
<p id="pmar">This isn’t the only case study involving amphetamine-induced trich, but it’s a bit more complicated. This study might be a bit more triggering.</p>
<p id="pmar">A 26-year-old male with ADHD was admitted for 3-4 weeks of compulsive hair pulling using tweezers. The patient had a complicated history with amphetamines (both prescribed and illicit) as well as antipsychotics. A month prior to admission, he began plucking ingrown pubic hairs, feeling tension then release, as well as “improving his ‘sex drive’ “. He then began pulling hairs from the side of his head, feeling that “these hairs may have been wrapped around internal organs”. He shaved his head to decrease urges to pluck. He also believed hairs were responsible for misalignment of his jaw and neck and pulling would also increase blood flow. The patient had a history of experimenting with hallucinogens. Unsurprisingly, the patient was admitted to an inpatient locked psychiatry unit.</p>
<p id="pmar">Narine, Chiranjir, Sajjad R. Sarwar, and Theodor B. Rais. “Adderall-Induced Trichotillomania: A Case Report.” Innovations in Clinical Neuroscience 10.7-8 (2013): 13–14. Print.</p>
<p id="pmar">Hamalian, Gareen, and Leslie Citrome. "Stimulant-induced trichotillomania." Substance abuse 31.1 (2010): 68-70.</p>
<?php include "includes/footer.php"?>